{
	"version": 1530543964,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/background.png",
		"images/menu_box-sheet0.png",
		"images/font.png",
		"images/obj_global-sheet0.png",
		"images/obj_window-sheet0.png",
		"images/obj_button_icon-sheet0.png",
		"images/obj_button_icon-sheet1.png",
		"images/obj_button_icon-sheet2.png",
		"images/obj_icons-sheet0.png",
		"images/obj_icons-sheet1.png",
		"images/level4-sheet0.png",
		"images/level5-sheet0.png",
		"images/level6-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tiledbackground.png",
		"images/tilemap.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/anjinglaut-sheet0.png",
		"images/anjinglaut-sheet1.png",
		"images/anjinglaut-sheet2.png",
		"images/3smallnihyes-sheet0.png",
		"images/badak-sheet0.png",
		"images/obj_health-sheet0.png",
		"images/obj_health-sheet1.png",
		"images/gemboknih-sheet0.png",
		"media/rollover2.m4a",
		"media/rollover2.ogg",
		"media/level 2.m4a",
		"media/level 2.ogg",
		"media/level 1.m4a",
		"media/level 1.ogg",
		"media/level 3.m4a",
		"media/level 3.ogg",
		"media/'africa marimba adventure!' fun upbeat game music by heatleybros.m4a",
		"media/'africa marimba adventure!' fun upbeat game music by heatleybros.ogg",
		"media/'amazon jungle adventure!' wild fun game music by heatleybros (online-audio-converter.com).m4a",
		"media/'amazon jungle adventure!' wild fun game music by heatleybros (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}